### PR TITLE
Add install/uninstall scripts

### PR DESCRIPTION
**Pull request by pepibumur**
This PR adds a couple of scripts for installing and uninstalling the app by just running a command on the terminal.

Resolves #6

### CODE REVIEW

**Comment by pepibumur** [comment]
@esttorhe would you mind running the command and see if it works for you?

**Comment by esttorhe** [comment]
Let me pull and test

I'll update the issue with the results

**Comment by esttorhe** [comment]
@pepibumur Pointing the command to run against `https://raw.githubusercontent.com/xcbuddy/xcbuddy/0bbad8ea0b0d894f9a53b1ec1521677f9e521071/scripts/install` it works as expected

can even use
```console
xcbuddy```

So once you merge that link to `master` will work as expected 👍

**Comment by pepibumur** [comment]
You shouldn't need to pull, just run the script on the PR:

```bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/xcbuddy/xcbuddy/master/scripts/install)"
```

**Comment by esttorhe** [comment]
I didn't pull. But running that command would file since the command points to the matter tree and this pr is the one that introduces the file to the tree. 

All I did was run the command against the file in the pr and it worked. Once you merge the command in the ReadMe will work

**Comment by esttorhe** [comment]
*fail

**Comment by esttorhe** [comment]
*master

Sorry. Replying from the phone while walking 😅

**Pull request merged**
